/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPack;

import static java.awt.PageAttributes.ColorType.COLOR;
import java.sql.*;
import DataBase.*;
import SnakeGame.Window;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Cucc
 */
public class MainWindow extends javax.swing.JFrame {

    private String usernameEntry = "";
    private String emailEntry = "";
    private String passwdEntry = "";
    private String ipEntry = "";
    private static DBManager mng = null;
    private static User user = null;
    private static Window f1 = null;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();

        setLocationRelativeTo(null);
        
        firstWindow.setVisible(true);
        SignupWindow.setVisible(false);
        LoginPanel.setVisible(false);

        mng = new DBManager();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        loginUsername = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        loginPwd = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        firstWindow = new javax.swing.JPanel();
        signUpButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        SignupWindow = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        signup = new javax.swing.JButton();
        pwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        LoginPanel.setBackground(new java.awt.Color(0, 153, 153));

        loginUsername.setBackground(new java.awt.Color(0, 153, 153));
        loginUsername.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        loginUsername.setForeground(new java.awt.Color(204, 204, 204));
        loginUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginUsername.setText("username");
        loginUsername.setBorder(null);
        loginUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginUsernameFocusLost(evt);
            }
        });
        loginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameActionPerformed(evt);
            }
        });

        loginPwd.setBackground(new java.awt.Color(0, 153, 153));
        loginPwd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginPwd.setForeground(new java.awt.Color(204, 204, 204));
        loginPwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginPwd.setText("password");
        loginPwd.setBorder(null);
        loginPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginPwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginPwdFocusLost(evt);
            }
        });

        login.setBackground(new java.awt.Color(0, 153, 153));
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.setBorder(signUpButton.getBorder());
        login.setPreferredSize(new java.awt.Dimension(80, 43));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(loginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(loginPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(loginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        firstWindow.setBackground(new java.awt.Color(0, 0, 102));
        firstWindow.setName(""); // NOI18N
        firstWindow.setPreferredSize(new java.awt.Dimension(400, 300));

        signUpButton.setBackground(new java.awt.Color(0, 51, 153));
        signUpButton.setForeground(new java.awt.Color(255, 255, 255));
        signUpButton.setText("Sign up");
        signUpButton.setBorder(null);
        signUpButton.setBorderPainted(false);
        signUpButton.setFocusPainted(false);
        signUpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signUpButton.setPreferredSize(new java.awt.Dimension(80, 43));
        signUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpButtonMouseClicked(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(0, 51, 153));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setBorder(null);
        loginButton.setBorderPainted(false);
        loginButton.setFocusPainted(false);
        loginButton.setPreferredSize(new java.awt.Dimension(80, 43));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout firstWindowLayout = new javax.swing.GroupLayout(firstWindow);
        firstWindow.setLayout(firstWindowLayout);
        firstWindowLayout.setHorizontalGroup(
            firstWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstWindowLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        firstWindowLayout.setVerticalGroup(
            firstWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstWindowLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(firstWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        SignupWindow.setBackground(new java.awt.Color(102, 0, 102));
        SignupWindow.setEnabled(false);

        username.setBackground(new java.awt.Color(102, 0, 102));
        username.setColumns(10);
        username.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText("username");
        username.setToolTipText("");
        username.setBorder(null);
        username.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        username.setDoubleBuffered(true);
        username.setSelectionColor(new java.awt.Color(102, 0, 102));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });

        jSeparator1.setOpaque(true);
        jSeparator1.setRequestFocusEnabled(false);
        jSeparator1.setVerifyInputWhenFocusTarget(false);

        jSeparator2.setOpaque(true);
        jSeparator2.setRequestFocusEnabled(false);
        jSeparator2.setVerifyInputWhenFocusTarget(false);

        email.setBackground(new java.awt.Color(102, 0, 102));
        email.setColumns(10);
        email.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        email.setForeground(new java.awt.Color(153, 153, 153));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setText("email");
        email.setToolTipText("");
        email.setBorder(null);
        email.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        email.setDoubleBuffered(true);
        email.setSelectionColor(new java.awt.Color(102, 0, 102));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });

        jSeparator3.setOpaque(true);
        jSeparator3.setRequestFocusEnabled(false);
        jSeparator3.setVerifyInputWhenFocusTarget(false);

        signup.setBackground(new java.awt.Color(0, 0, 102));
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("Sign up");
        signup.setBorder(null);
        signup.setBorderPainted(false);
        signup.setFocusPainted(false);
        signup.setPreferredSize(new java.awt.Dimension(75, 35));
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });

        pwd.setBackground(new java.awt.Color(102, 0, 102));
        pwd.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        pwd.setForeground(new java.awt.Color(153, 153, 153));
        pwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwd.setText("pwd");
        pwd.setBorder(null);
        pwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdFocusLost(evt);
            }
        });

        javax.swing.GroupLayout SignupWindowLayout = new javax.swing.GroupLayout(SignupWindow);
        SignupWindow.setLayout(SignupWindowLayout);
        SignupWindowLayout.setHorizontalGroup(
            SignupWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupWindowLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupWindowLayout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addGroup(SignupWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(email)
                    .addComponent(jSeparator3)
                    .addComponent(pwd))
                .addGap(215, 215, 215))
        );
        SignupWindowLayout.setVerticalGroup(
            SignupWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupWindowLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(firstWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SignupWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(firstWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SignupWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseClicked
        // TODO add your handling code here:

        firstWindow.setVisible(false);
        SignupWindow.setVisible(true);

    }//GEN-LAST:event_signUpButtonMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        
        firstWindow.setVisible(false);
        LoginPanel.setVisible(true);
        
    }//GEN-LAST:event_loginButtonMouseClicked

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        email.setBackground(new java.awt.Color(102, 0, 102));
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText(emailEntry);
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        email.setForeground(new java.awt.Color(153, 153, 153));
        emailEntry = email.getText();
        email.setText(emailEntry);
    }//GEN-LAST:event_emailFocusLost

    private void pwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdFocusGained
        // TODO add your handling code here:
        //pwd.setBackground(new java.awt.Color(102, 0, 102));
        pwd.setForeground(new java.awt.Color(255, 255, 255));
        pwd.setText(passwdEntry);
    }//GEN-LAST:event_pwdFocusGained

    private void pwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdFocusLost
        // TODO add your handling code here:
        pwd.setForeground(new java.awt.Color(153, 153, 153));
        passwdEntry = pwd.getText();
        pwd.setText(passwdEntry);
    }//GEN-LAST:event_pwdFocusLost

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        username.setForeground(new java.awt.Color(153, 153, 153));
        usernameEntry = username.getText();
        username.setText(usernameEntry);
    }//GEN-LAST:event_usernameFocusLost

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        //username.setBackground(new java.awt.Color(102, 0, 102));
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText(usernameEntry);
    }//GEN-LAST:event_usernameFocusGained

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked

        try {
            // TODO add your handling code here:

            if (mng.checkIfUsrExists(usernameEntry)) {
                
                showMessageDialog(null, "User already exists!\nLogin please!");
                
                SignupWindow.setVisible(false);
                LoginPanel.setVisible(true);
                passwdEntry = "";
                
            } else {
                
                System.out.println("Not exists, created now...");

                user = new User(usernameEntry, passwdEntry, emailEntry);
                mng.addNewUser(user);
                
                f1 = new Window();

                setVisible(false);
                
                //Setting up the window settings
                f1.setTitle("Snake");
                f1.setBackground(Color.green);
                f1.setSize(600, 600);
                f1.setVisible(true);
                f1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            }
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_signupMouseClicked

    private void loginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameActionPerformed

    private void loginUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUsernameFocusGained
        // TODO add your handling code here:
        
        loginUsername.setForeground(new java.awt.Color(255, 255, 255));
        loginUsername.setText(usernameEntry);
        
    }//GEN-LAST:event_loginUsernameFocusGained

    private void loginUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUsernameFocusLost
        // TODO add your handling code here:
        
        loginUsername.setForeground(new java.awt.Color(153, 153, 153));
        usernameEntry = loginUsername.getText();
        loginUsername.setText(usernameEntry);
        
    }//GEN-LAST:event_loginUsernameFocusLost

    private void loginPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginPwdFocusGained
        // TODO add your handling code here:
        
        loginPwd.setForeground(new java.awt.Color(255, 255, 255));
        loginPwd.setText(passwdEntry);
        
    }//GEN-LAST:event_loginPwdFocusGained

    private void loginPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginPwdFocusLost
        // TODO add your handling code here:
        
        loginPwd.setForeground(new java.awt.Color(153, 153, 153));
        passwdEntry = loginPwd.getText();
        loginPwd.setText(passwdEntry);
        
    }//GEN-LAST:event_loginPwdFocusLost

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        
        if(mng.checkIfUsrExists(usernameEntry, passwdEntry)){
            
            user = new User(usernameEntry);
            
            f1 = new Window();

                setVisible(false);
                
                //Setting up the window settings
                f1.setTitle("Snake");
                f1.setSize(600, 600);
                f1.setVisible(true);
                f1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            
        } else {
            
            showMessageDialog(null, "Wrong username or password!\nTry again!");
            
        }
        
    }//GEN-LAST:event_loginMouseClicked

    public static DBManager getManager(){
        return mng;
    }
    
    public static User getUser(){
        return user;
    }
    
    public static Window getWindow(){
        return f1;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel SignupWindow;
    private javax.swing.JTextField email;
    private javax.swing.JPanel firstWindow;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton login;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField loginPwd;
    private javax.swing.JTextField loginUsername;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JButton signUpButton;
    private javax.swing.JButton signup;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
